services:
  alist:
    image: xhofe/alist:latest
    ports:
      - "5244:5244"
    volumes:
      - alist-data:/opt/alist/data
    labels:
      dev.okteto.com/auto-ingress: "domain"
volumes:
  alist-data:
    driver_opts:
      size: 1Gi