services:
  alist:
    image: xhofe/alist:latest
    ports:
      - "5244:5244"
    volumes:
      - alist-data:/opt/alist/data
  cloudflare:
        image: cloudflare/cloudflared:latest
        environment:
            - CF_TOKEN=${CF_TOKEN}   
        entrypoint: cloudflared tunnel --no-autoupdate run --token ${CF_TOKEN}
volumes:
  alist-data:
    driver_opts:
      size: 1Gi